repos:
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.16.0"
    hooks:
      - id: terraform-docs-go
        args: ["markdown", "table", "--output-file", "README.md", "."]
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.0
    hooks:
      - id: terraform_fmt
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: no-commit-to-branch # protects main and master by default
      - id: end-of-file-fixer
      - id: check-case-conflict
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v2.1.0"
    hooks:
      - id: prettier
        exclude_types: ["json", "python", "terraform", "markdown"]
        args: ["--ignore-unknown"]
